org: felipstein
service: servereless-template-api

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: sa-east-1
  # Exemplary feature
  iam:
    role:
      statements:
        - Effect: Allow
          Action: s3:PutObject
          Resource: <BUCKET ARN>

package:
  individually: true

build:
  esbuild:
    bundle: true
    minify: true
    sourcemap: false
    exclude:
      - '@aws-sdk/*'

# Exemplary lambda functions
functions:
  upload:
    handler: src/main/functions/upload.handler
    events:
      - httpApi:
          path: /upload
          method: POST
  users:
    handler: src/main/functions/users.handler
    events:
      - httpApi:
          path: /users
          method: ANY
      - httpApi:
          path: /users/{param+}
          method: ANY
